// Mocks generated by Mockito 5.4.6 from annotations
// in opennutritracker/test/features/recipes/presentation/screens/import_recipe_scanner_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:opennutritracker/core/domain/entity/recipe_entity.dart' as _i2;
import 'package:opennutritracker/core/domain/usecase/save_recipe_usecase.dart'
    as _i3;
import 'package:opennutritracker/features/recipes/presentation/bloc/recipes_bloc.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecipeEntity_0 extends _i1.SmartFake implements _i2.RecipeEntity {
  _FakeRecipeEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SaveRecipeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveRecipeUseCase extends _i1.Mock implements _i3.SaveRecipeUseCase {
  MockSaveRecipeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RecipeEntity> save(
    _i2.RecipeEntity? recipe, {
    bool? totalWeightOverridden = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #save,
              [recipe],
              {#totalWeightOverridden: totalWeightOverridden},
            ),
            returnValue: _i4.Future<_i2.RecipeEntity>.value(
              _FakeRecipeEntity_0(
                this,
                Invocation.method(
                  #save,
                  [recipe],
                  {#totalWeightOverridden: totalWeightOverridden},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.RecipeEntity>);
}

/// A class which mocks [RecipesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipesBloc extends _i1.Mock implements _i5.RecipesBloc {
  MockRecipesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.RecipesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.dummyValue<_i5.RecipesState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.RecipesState);

  @override
  _i4.Stream<_i5.RecipesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i5.RecipesState>.empty(),
          )
          as _i4.Stream<_i5.RecipesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.RecipesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.RecipesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.RecipesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.RecipesEvent>(
    _i7.EventHandler<E, _i5.RecipesState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i5.RecipesEvent, _i5.RecipesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.RecipesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onChange(_i7.Change<_i5.RecipesState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
